# Generated by Django 5.0.2 on 2024-08-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='IUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
