# Generated by Django 5.0.2 on 2024-08-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0005_signiniuser_rename_iuser_singupiuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SingUpIUser',
            new_name='SignUpIUser',
        ),
    ]
