# Generated by Django 5.0.2 on 2024-08-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0006_rename_singupiuser_signupiuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupiuser',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
