# Generated by Django 5.0.2 on 2024-08-31 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0007_alter_signupiuser_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignInIUser',
        ),
        migrations.DeleteModel(
            name='SignUpIUser',
        ),
    ]
