# Generated by Django 5.0.2 on 2024-08-29 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_cart_cartitem_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
